import test from 'node:test'
import assert from 'node:assert/strict'
import fs from 'node:fs'
import path from 'node:path'
import { APP_VERSION } from '../src/version.js'

// ---------------------------------------------------------------------------
// `src/version.ts` is generated by `build.js` from `package.json` and committed anyway, because the
// React Native bundler reads `src/` directly and never runs `build.js`. That is the whole reason it
// is in the repository, and it is also the reason it can lie: the desktop regenerates the file on
// every build, so a stale value there is invisible — while mobile ships exactly what was committed.
//
// v1.14.61 went out that way. `package.json` and the tag said 1.14.61, the committed constant still
// said 1.14.60, and the profile screen on every phone running that release reads "Linda 1.14.60".
// The four tags before it were consistent, so this is not chronic drift — it is one bump that
// skipped a build, which is precisely the kind of thing nobody notices until someone is trying to
// work out which version a bug report came from.
// ---------------------------------------------------------------------------

test('the committed version matches package.json, because mobile ships the committed one', () => {
  const pkg = JSON.parse(fs.readFileSync(path.join(process.cwd(), 'package.json'), 'utf8')) as { version: string }

  assert.equal(
    APP_VERSION,
    pkg.version,
    'src/version.ts is stale — run `npm run build` to regenerate it, then commit the result. ' +
      'The desktop regenerates this at build time and will look fine; mobile will ship the old number.'
  )
})
