import esbuild from 'esbuild'
import fs from 'node:fs'

const watch = process.argv.includes('--watch')

// Keeps src/version.ts honest: the apps have no other way to say which build they are, which
// turned "is your desktop actually running the version with the fix?" into an unanswerable
// question during a bug hunt.
const { version } = JSON.parse(fs.readFileSync('package.json', 'utf8'))
fs.writeFileSync('src/version.ts',
  '// Generated by build.js from package.json — do not edit by hand.\n' +
  '// Committed because the mobile bundler reads src/ directly and never runs build.js.\n' +
  `export const APP_VERSION = '${version}'\n`)

const options = {
  entryPoints: ['src/main.ts'],
  outfile: 'dist/app.js',
  bundle: true,
  format: 'cjs',
  platform: 'node',
  target: 'es2022',
  packages: 'external',
  sourcemap: true,
  logLevel: 'info'
}

if (watch) {
  const ctx = await esbuild.context(options)
  await ctx.watch()
  console.log('watching for changes...')
} else {
  await esbuild.build(options)
}
